# Generated by Django 4.0.6 on 2022-08-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=400, null=True)),
                ('name', models.CharField(max_length=50)),
                ('kakao_id', models.IntegerField(null=True)),
                ('backjoon_id', models.CharField(max_length=50, null=True)),
                ('checked_social', models.BooleanField()),
                ('user_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
