# Generated by Django 3.2.14 on 2022-08-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_kakao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_pwd',
        ),
    ]
